### ISSUE TITLE
Tüyo #1

### ISSUE THREAD

**Issue by omerakgoz34** [Serhatpars/BiscuitCss#1]
* Her sürümü Release olarak yayınlarsan hem yönetmesi daha kolay olur hemde indirmesi :)

* GitHub'ın kullandığı AWS sunucuları Türkiye'ye yavaş bir indirme hızı verse de fazla büyük bir şey olmayacağından sorun olmaz.

**Comment by Serhatpars** [comment]
Bunu Yapacağım.
